### ISSUE TITLE
AddDictionaryEntries wrong http method

### ISSUE THREAD

**Issue by myperl** [bengentil/textrazor-go#1]
Hi, 

thank you for the great work!

IMHO there is little problem with the function AddDictionaryEntries. According to Textrazor doku this is called as POST. In the source code there is a PUT.

best regards 
Thomas

**Comment by bengentil** [comment]
Hi Thomas,

Good catch ;)

I don't play with this API anymore but if it's useful for you don't hesitate to create other issues or PRs
I'll try to respond ;)

Regards,
Benjamin
